"""
score_full_matrix.py
======================
Scores the full 24-combination LayerRoute + LayerDrop supplemental matrix
(2 tasks x 2 scales x 3 seeds x 2 methods), using the CORRECTED result
files from this session (SKIPFIX for GSM8K, LENFIX for CNN/DM -- both
fixes are cumulative; LENFIX files already include the SKIPFIX inference
skip mechanism since they were generated by the same, twice-fixed
gated_qwen.py / run_layerroute_timed.py).

Accuracy: exact-match on #### answer (GSM8K), ROUGE-L (CNN/DM).
Cost: ms/token (routed vs baseline), speedup ratio.
Reports per-seed values and 3-seed means for both methods, both metrics,
all 4 task x scale combinations.
"""
import json
import re
import glob
from rouge_score import rouge_scorer

scorer = rouge_scorer.RougeScorer(["rougeL"], use_stemmer=True)


def extract_gsm8k_answer(text):
    m = re.findall(r"####\s*(-?[\d,]+(?:\.\d+)?)", text)
    return m[0].replace(",", "").strip() if m else None


def score_gsm8k(records):
    correct = 0
    for r in records:
        pred = extract_gsm8k_answer(r["generated_text"])
        gold = extract_gsm8k_answer(r["gold"])
        if pred is not None and pred == gold:
            correct += 1
    return correct / len(records)


def extract_summary(text, stop_marker="\nArticle:", max_words=100):
    idx = text.find(stop_marker)
    text = text[:idx].strip() if idx != -1 else text.strip()
    words = text.split()
    return " ".join(words[:max_words]) if len(words) > max_words else text


def score_cnndm(records):
    scores = []
    for r in records:
        pred = extract_summary(r["generated_text"])
        gold = r["gold"]
        if not pred or not gold:
            scores.append(0.0)
            continue
        scores.append(scorer.score(gold, pred)["rougeL"].fmeasure)
    return sum(scores) / len(scores)


def cost_stats(records):
    ms_routed = sum(r["pure_inference_ms"] / max(r["new_tokens"], 1) for r in records) / len(records)
    ms_base = sum(r["baseline_ms"] / max(r["baseline_new_tokens"], 1) for r in records) / len(records)
    return ms_routed, ms_base, ms_base / ms_routed


def load(path):
    with open(path) as f:
        return json.load(f)["records"]


METHODS = {
    "LayerRoute": {
        "gsm8k": "results/layerroute_timed_gsm8k_{scale}_seed{seed}_SKIPFIX/layerroute_query_costs.json",
        "cnndm": "results/layerroute_timed_cnndm_{scale}_seed{seed}_LENFIX/layerroute_query_costs.json",
    },
    "LayerDrop": {
        "gsm8k": "results/layerdrop_timed_gsm8k_{scale}_seed{seed}/layerdrop_query_costs.json",
        "cnndm": "results/layerdrop_timed_cnndm_{scale}_seed{seed}_LENFIX/layerdrop_query_costs.json",
    },
}

SEEDS = [2024, 42, 123]
SCALES = ["05b", "15b"]
TASKS = ["gsm8k", "cnndm"]

for method, paths in METHODS.items():
    print(f"\n{'='*70}\n{method}\n{'='*70}")
    for task in TASKS:
        for scale in SCALES:
            accs, speedups, ms_routed_list, ms_base_list = [], [], [], []
            for seed in SEEDS:
                path = paths[task].format(scale=scale, seed=seed)
                try:
                    records = load(path)
                except FileNotFoundError:
                    print(f"  {task}/{scale}/seed{seed}: MISSING FILE ({path})")
                    continue
                acc = score_gsm8k(records) if task == "gsm8k" else score_cnndm(records)
                ms_r, ms_b, spd = cost_stats(records)
                accs.append(acc)
                speedups.append(spd)
                ms_routed_list.append(ms_r)
                ms_base_list.append(ms_b)
                metric_name = "acc" if task == "gsm8k" else "rougeL"
                print(f"  {task}/{scale}/seed{seed}: {metric_name}={acc:.3f}  "
                     f"routed_ms/tok={ms_r:.2f}  base_ms/tok={ms_b:.2f}  speedup={spd:.2f}x")
            if accs:
                mean_acc = sum(accs) / len(accs)
                mean_spd = sum(speedups) / len(speedups)
                mean_mr = sum(ms_routed_list) / len(ms_routed_list)
                mean_mb = sum(ms_base_list) / len(ms_base_list)
                print(f"  >>> {task}/{scale} MEAN (n={len(accs)}): "
                     f"acc={mean_acc:.3f}  routed_ms/tok={mean_mr:.2f}  "
                     f"base_ms/tok={mean_mb:.2f}  speedup={mean_spd:.2f}x")
